name: ProtocolVanish
author: YourPalJake
main: com.azortis.protocolvanish.bukkit.ProtocolVanish
version: 1.0
api-version: 1.15
loadbefore: [Essentials]
depend: [ProtocolLib, PlaceholderAPI]
softdepend: [Essentials]